ALTER TABLE category_rules ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 999;
ALTER TABLE category_rules ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE category_rules ADD COLUMN IF NOT EXISTS label TEXT NOT NULL DEFAULT '';
ALTER TABLE category_rules ADD COLUMN IF NOT EXISTS auto_reply_enabled BOOLEAN NOT NULL DEFAULT false;
